[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_2023"

[dependencies]
advent-of-code = { path = "../common/" }
nom = "7.1.3"

[dev-dependencies]
rand = "0.8.5"
