[package]
name = "advent-of-code-2022"
version = "0.2.0"
edition = "2021"

[lib]
name = "aoc_2022"

[dependencies]
advent-of-code = { path = "../common/"}

[dev-dependencies]
criterion = "0.4"
rand = "0.8.5"

[[bench]]
name = "benches"
harness = false

